apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo_app
spec:
  selector:
    matchLabels:
      app: todo_app
  replicas: 2
  template:
    metadata:
      labels:
        app: todo_app
    spec:
      containers:
      - name: todo_app
        image: lalithtrs/todo_app:1.1
        ports:
        - containerPort: 8000
